export default {
    /* RI data */
    AWS_GET_RI_DATA: 'AWS_GET_RI_DATA',
    AWS_GET_RI_DATA_SUCCESS_EC2: 'AWS_GET_RI_DATA_SUCCESS_EC2',
    AWS_GET_RI_DATA_SUCCESS_RDS: 'AWS_GET_RI_DATA_SUCCESS_RDS',
    AWS_GET_RI_DATA_ERROR: 'AWS_GET_RI_DATA_ERROR',
  };
  